name: araimo
description: A smart streaming application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # UI & Icons
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  marquee: ^2.2.3
  cached_network_image: ^3.3.1
  
  # Player & Media
  video_player: ^2.8.2
  chewie: ^1.7.5
  wakelock_plus: ^1.1.4
  
  # Logic & Data
  http: ^1.2.0
  provider: ^6.1.1
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # Icon Generator
  flutter_launcher_icons: ^0.13.1

# App Icon Configuration
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
