name: araimo
description: A smart sports streaming application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  marquee: ^2.2.3
  flutter_spinkit: ^5.2.0  # Added for Loading Animation
  
  # Player
  pod_player: ^0.3.1       # mxlive player
  wakelock_plus: ^1.1.4
  
  # Network & Cache
  http: ^1.2.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  
  # Utils
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
